# syntax=docker/dockerfile:1
FROM golang:1.22.4-bookworm

ARG ANVIL_TAG=nightly-2cdbfaca634b284084d0f86357623aef7a0d2ce3

WORKDIR /usr/src/app
COPY go.mod go.sum ./
RUN go mod download && go mod verify

COPY . .

CMD ["go", "run", "main.go"]
