version: '3.8'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./restore.sql:/docker-entrypoint-initdb.d/restore.sql
      - ./data_files/:/docker-entrypoint-initdb.d/data_files
  postgraphile:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - db
    ports:
      - "5001:5000"

volumes:
  pgdata: